
[font]
size = 10.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
# family = "Cousine Nerd Font"
style = "regular"

[window.dimensions]
columns = 160
lines = 45

[scrolling]
history = 50000

[general]
import = [
	"~/.config/alacritty/themes/custom1.toml"
]
