
[font]
size = 11.0

[font.normal]
family = "CaskaydiaMono Nerd Font"
# family = "Cousine Nerd Font"
style = "regular"

[window.dimensions]
columns = 160
lines = 45

[scrolling]
history = 25000

[general]
import = [
	"~/.config/alacritty/themes/custom1.toml"
]
